### ISSUE TITLE
Investigate Kubernetes TypeScript client

### ISSUE THREAD

**Issue by radu-matei** [radu-matei/kube-bot#2]
The [Kubernetes TypeScript client](https://github.com/kubernetes-client/typescript) might be much simpler to integrate with the Node BotFramework SDK - if it works.

The issue right now is that according to this issue - https://github.com/kubernetes-client/typescript/issues/4 - you cannot use with self-signed certificates.

**Comment by brendandburns** [comment]
@radu-matei it's not that you can't use self-signed certs, it's that you can't ignore CA errors.

If you have the certificate authority cert [e.g. ca.crt] which generally you do in a minikube or otherwise cluster then it will work.

(and I'll add explicit ignore cert-errors support quite soon...)

**Comment by brendandburns** [comment]
actually, I checked in the code already, closing kubernetes-client/typescript#4

**Comment by radu-matei** [comment]
@brendandburns - thanks a lot for replying, I will look into the TypeScript client then.
Closing this.
